=== liadomide/EduPack/tvb-framework/tvb/core/schema/tvb.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:annotation>
    	<xs:documentation>
	    	This is a validation XML schema.
			You should use this in case you intend to produce TVB compatible interfaces.
			You are expected to write your algorithms in some programming language (e.g. Matlab, Python) and then describe its interface in an XML file.
			The XML file, if compatible with this XSD, will be parsable by TVB, thus integrated in TVB's UI and results processed by our visualizers.
		</xs:documentation>
	</xs:annotation>

	<xs:simpleType name="alfaNumericString">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
			<xs:pattern value="[a-zA-Z0-9]*" />
		</xs:restriction>
	</xs:simpleType>

    <xs:element name="tvb">
        <xs:complexType>
            <xs:all>
                <xs:element name="algorithm_group" type="algorithmGroupType"/>
            </xs:all>
        </xs:complexType>
    </xs:element>


    <xs:complexType name="algorithmGroupType">
        <xs:sequence>
            <xs:element name="algorithm" type="algorithmType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="type" type="xs:string" use="required"/>
        <xs:attribute name="uiName" type="xs:string" use="required"/>
        <xs:attribute name="description" type="xs:string" use="optional"/>
        <xs:attribute name="label" type="xs:string" use="required"/>
        <xs:attribute name="additionalPath" type="xs:string" use="optional"/>
        <xs:attribute name="subsection" type="xs:string" use="optional"/>
    </xs:complexType>


    <xs:complexType name="algorithmType">
        <xs:sequence>
            <xs:element name="code" type="codeType"/>
            <xs:element name="matlab_file" type="codeType" minOccurs="0"/>
            <xs:element name="inputs" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="input" type="inputType" minOccurs="1" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="outputs" type="outputsType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="identifier" type="alfaNumericString" use="required"/>
    </xs:complexType>


    <xs:complexType name="codeType">
        <xs:attribute name="value" type="xs:string" use="required"/>
        <xs:attribute name="import" type="xs:string" use="optional"/>
    </xs:complexType>


    <xs:complexType name="inputType">
        <xs:sequence>
            <xs:element name="name">
                <xs:complexType>
                    <xs:attribute name="value" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="label">
                <xs:complexType>
                    <xs:attribute name="value" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="description" minOccurs="0">
                <xs:complexType>
                    <xs:attribute name="value" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="type" type="type"/>
        </xs:sequence>
        <xs:attribute name="required" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="True"/>
                    <xs:enumeration value="False"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="overwrite" type="xs:string" use="optional"/>
    </xs:complexType>


    <xs:complexType name="type">
        <xs:sequence>
            <xs:element name="options" type="optionsType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="conditions" type="conditionsType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="pre_process" type="preProcessType" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="value" type="xs:string" use="required"/>
        <xs:attribute name="field" type="xs:string" use="optional"/>
        <xs:attribute name="initparam" type="xs:string" use="optional"/>
        <xs:attribute name="default" type="xs:string" use="optional"/>
        <xs:attribute name="minValue" type="xs:string" use="optional"/>
        <xs:attribute name="maxValue" type="xs:string" use="optional"/>
    </xs:complexType>

    <xs:complexType name="preProcessType">
        <xs:sequence>
            <xs:element name="python_method" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                    <xs:attribute name="value" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="ui_method" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                    <xs:attribute name="value" type="xs:string" use="required"/>
                    <xs:attribute name="parameters_prefix" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="parameters" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="parameter" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:attribute name="name" type="xs:string" use="required"/>
                                <xs:attribute name="value" type="xs:string" use="required"/>
                                <xs:attribute name="operations" type="xs:string" use="optional"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="conditionsType">
        <xs:sequence>
            <xs:element name="cond_fields" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                    <xs:attribute name="value_list" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="cond_operations" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                    <xs:attribute name="value_list" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="cond_values" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                    <xs:attribute name="value_list" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="optionsType">
        <xs:sequence>
            <xs:element name="option" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:all>
                        <xs:element name="inputs" minOccurs="0">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="input" type="inputType" minOccurs="1" maxOccurs="unbounded"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:all>
                    <xs:attribute name="name" type="xs:string" use="required"/>
                    <xs:attribute name="value" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="outputsType">
        <xs:sequence>
            <xs:element name="output" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="field" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:attribute name="name" type="xs:string" use="required"/>
                                <xs:attribute name="reference" type="xs:string" use="optional"/>
                                <xs:attribute name="value" type="xs:string" use="optional"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="type" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== liadomide/EduPack/tvb-framework/tvb/adapters/portlets/bct_portlets.xml
<?xml version="1.0"?>
 
		
<tvb xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../core/schema/tvb.xsd">

    <algorithm_group name="simple_portlet" type="" uiName="Simple Python Portlets" label="Selected Portlet:">
        
        <!--  For each portlet, a preview with the name $identifider$.png should be present in:
        	 tvb/interfaces/static/style/img/portlets 
        	 and a style in section_burst.css
       -->
        <algorithm name="BCT - Clustering Coeficient WD" identifier="CCWD">
            <code value=""/>
            <inputs>
                <input>
                    <name value="chain_1"/>
                    <label value="First adapter from chain"/>
                    <type value="tvb.adapters.analyzers.group_matlab_adapter.MatlabAdapter" initparam="adapters/analyzers/matlab_interfaces/bct_clustering.xml" field="bct" default="CCWD"/>
                </input>
                <input overwrite="chain_1">
                    <name value="bct_parameters_option_CCWD_A"/>
                    <label value="Overwrite with first input of the simulator adapter."/>
                    <type value="dynamic" default="step_0[connectivity]" />
                </input>
                
                <input>
                    <name value="chain_2"/>
                    <label value="Second adapter from chain"/>
                    <type value="tvb.adapters.visualizers.histogram.HistogramViewer" field=""/>
                </input>
                <input overwrite="chain_2">
                	<name value="input_data"/>
                	<label value="Overwrite input_data parameter of second adapter with the first release of the first adapter."/>
                	<type value="dynamic" default="step_1[0]"/>
                </input>
                
            </inputs>
        </algorithm>
        
        <algorithm name="BCT - Node Betweenness Centrality Binary" identifier="NBCB">
            <code value=""/>
            <inputs>
                <input>
                    <name value="chain_1"/>
                    <label value="First adapter from chain"/>
                    <type value="tvb.adapters.analyzers.group_matlab_adapter.MatlabAdapter" initparam="adapters/analyzers/matlab_interfaces/bct_centrality.xml" field="bct" default="NBCB"/>
                </input>
                <input overwrite="chain_1">
                    <name value="bct_parameters_option_NBCB_A"/>
                    <label value="Overwrite with first input of the simulator adapter."/>
                    <type value="dynamic" default="step_0[connectivity]" />
                </input>
                
                <input>
                    <name value="chain_2"/>
                    <label value="Second adapter from chain"/>
                    <type value="tvb.adapters.visualizers.histogram.HistogramViewer" field=""/>
                </input>
                <input overwrite="chain_2">
                	<name value="input_data"/>
                	<label value="Overwrite input_data parameter of second adapter with the first release of the first adapter."/>
                	<type value="dynamic" default="step_1[0]"/>
                </input>
                
            </inputs>
        </algorithm>
        
        <algorithm name="BCT - Instrength and Outstrength" identifier="ISOS">
            <code value=""/>
            <inputs>
                <input>
                    <name value="chain_1"/>
                    <label value="First adapter from chain"/>
                    <type value="tvb.adapters.analyzers.group_matlab_adapter.MatlabAdapter" initparam="adapters/analyzers/matlab_interfaces/bct_degree.xml" field="bct" default="ISOS"/>
                </input>
                <input overwrite="chain_1">
                    <name value="bct_parameters_option_ISOS_CIJ"/>
                    <label value="Overwrite with first input of the simulator adapter."/>
                    <type value="dynamic" default="step_0[connectivity]" />
                </input>
                
                <input>
                    <name value="chain_2"/>
                    <label value="Second adapter from chain"/>
                    <type value="tvb.adapters.visualizers.histogram.HistogramViewer" field=""/>
                </input>
                <input overwrite="chain_2">
                	<name value="input_data"/>
                	<label value="Overwrite input_data parameter of second adapter with the first release of the first adapter."/>
                	<type value="dynamic" default="step_1[0]"/>
                </input>
                
            </inputs>
        </algorithm>
        
        <algorithm name="BCT - Instrength and Outstrength- Topo" identifier="ISOSTOPO">
            <code value=""/>
            <inputs>
                <input>
                    <name value="chain_1"/>
                    <label value="First adapter from chain"/>
                    <type value="tvb.adapters.analyzers.group_matlab_adapter.MatlabAdapter" initparam="adapters/analyzers/matlab_interfaces/bct_degree.xml" field="bct" default="ISOS"/>
                </input>
                <input overwrite="chain_1">
                    <name value="bct_parameters_option_ISOS_CIJ"/>
                    <label value="Overwrite with first input of the simulator adapter."/>
                    <type value="dynamic" default="step_0[connectivity]" />
                </input>
                
                <input>
                    <name value="chain_2"/>
                    <label value="Second adapter from chain"/>
                    <type value="tvb.adapters.visualizers.mplh5_topographic.TopographicViewer" field=""/>
                </input>
                <input overwrite="chain_2">
                	<name value="data_0"/>
                	<label value="Overwrite data_0 parameter of second adapter with the first release of the first adapter."/>
                	<type value="dynamic" default="step_1[0]"/>
                </input>
                <input overwrite="chain_2">
                	<name value="data_1"/>
                	<label value="Overwrite data_1 parameter of second adapter with the second release of the first adapter."/>
                	<type value="dynamic" default="step_1[1]"/>
                </input>
                <input overwrite="chain_2">
                	<name value="data_2"/>
                	<label value="Overwrite data_2 parameter of second adapter with the third release of the first adapter."/>
                	<type value="dynamic" default="step_1[2]"/>
                </input>
                
            </inputs>
        </algorithm>
        
        <algorithm name="BCT - Strength and Weight" identifier="STW">
            <code value=""/>
            <inputs>
                <input>
                    <name value="chain_1"/>
                    <label value="First adapter from chain"/>
                    <type value="tvb.adapters.analyzers.group_matlab_adapter.MatlabAdapter" initparam="adapters/analyzers/matlab_interfaces/bct_degree.xml" field="bct" default="STW"/>
                </input>
                <input overwrite="chain_1">
                    <name value="bct_parameters_option_STW_CIJ"/>
                    <label value="Overwrite with first input of the simulator adapter."/>
                    <type value="dynamic" default="step_0[connectivity]" />
                </input>
                
                <input>
                    <name value="chain_2"/>
                    <label value="Second adapter from chain"/>
                    <type value="tvb.adapters.visualizers.mplh5_topographic.TopographicViewer" field=""/>
                </input>
                <input overwrite="chain_2">
                	<name value="data_0"/>
                	<label value="Overwrite data_0 parameter of second adapter with the first release of the first adapter."/>
                	<type value="dynamic" default="step_1[0]"/>
                </input>
                <input overwrite="chain_2">
                	<name value="data_1"/>
                	<label value="Overwrite data_1 parameter of second adapter with the second release of the first adapter."/>
                	<type value="dynamic" default="step_1[1]"/>
                </input>
                
            </inputs>
        </algorithm>
        
   </algorithm_group>
   
</tvb>

=== liadomide/EduPack/tvb/adapters/analyzers/matlab_interfaces/bct_distance.xml
<?xml version="1.0"?>
 
		
<tvb xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../core/schema/tvb.xsd">

    <algorithm_group name="bct" subsection="bctdistance" type="tvb.adapters.analyzers.group_matlab_adapter.MatlabAdapter" additionalPath="externals/BCT"
                     uiName="Distance Algorithms" description="Brain Connectivity Toolbox" label="Choose Distance Algorithm:">
        <!-- Distance -->

        <algorithm name="Reachability and distance matrices (Breadth-first search)" identifier="RDM">
            <code value="[R,D] = breadthdist(CIJ);"/>
            <matlab_file value="breadthdist.m"/>
            <inputs>
                <input required="True">
                    <name value="CIJ"/>
                    <label value="Binary (directed/undirected) connection matrix:"/>
                    <type value="tvb.datatypes.connectivity.Connectivity" field="weights"/>
                </input>
            </inputs>
            <outputs>
                <output type="tvb.datatypes.graph.ConnectivityMeasure">
                    <field name="array_data" reference="result['R']"/>
                    <field name="connectivity" reference="inputs['CIJ_gid']"/>
                    <field name="title" value="Reachability matrix"/>
                </output>
                <output type="tvb.datatypes.graph.ConnectivityMeasure">
                    <field name="array_data" reference="result['D']"/>
                    <field name="connectivity" reference="inputs['CIJ_gid']"/>
                    <field name="title" value="Distance matrix"/>
                </output>
            </outputs>
        </algorithm>

        <algorithm name="Distance binary matrix" identifier="DBIN">
            <code value="D = distance_bin(A);"/>
            <matlab_file value="distance_bin.m"/>
            <inputs>
                <input required="True">
                    <name value="A"/>
                    <label value="Binary (directed/undirected) connection matrix:"/>
                    <type value="tvb.datatypes.connectivity.Connectivity" field="weights"/>
                </input>
            </inputs>
            <outputs>
                <output type="tvb.datatypes.graph.ConnectivityMeasure">
                    <field name="array_data" reference="result['D']"/>
                    <field name="connectivity" reference="inputs['A_gid']"/>
                    <field name="title" value="Distance matrix"/>
                </output>
            </outputs>
        </algorithm>

        <algorithm name="Distance weighted matrix" identifier="DWEI">
            <code value="D = distance_wei(A);"/>
            <matlab_file value="distance_wei.m"/>
            <inputs>
                <input required="True">
                    <name value="A"/>
                    <label value="Weighted (directed/undirected) connection matrix:"/>
                    <type value="tvb.datatypes.connectivity.Connectivity" field="weights"/>
                </input>
            </inputs>
            <outputs>
                <output type="tvb.datatypes.graph.ConnectivityMeasure">
                    <field name="array_data" reference="result['D']"/>
                    <field name="connectivity" reference="inputs['A_gid']"/>
                    <field name="title" value="Distance matrix"/>
                </output>
            </outputs>
        </algorithm>

        <algorithm name="Network walks" identifier="NETW">
            <code value="[Wq,twalk,wlq]  = findwalks(A);"/>
            <matlab_file value="findwalks.m"/>
            <inputs>
                <input required="True">
                    <name value="A"/>
                    <label value="Binary (directed/undirected) connection matrix:"/>
                    <type value="tvb.datatypes.connectivity.Connectivity" field="weights"/>
                </input>
            </inputs>
            <outputs>
                <output type="tvb.datatypes.graph.ConnectivityMeasure">
                    <field name="array_data" reference="result['Wq']"/>
                    <field name="connectivity" reference="inputs['A_gid']"/>
                    <field name="title" value="3D matrix"/>
                </output>
                <output type="tvb.datatypes.mapped_values.ValueWrapper">
                    <field name="data_value" reference="float(result['twalk'])"/>
                    <field name="data_type" value="float"/>
                    <field name="data_name" value="Total number of walks found"/>
                </output>
                <output type="tvb.datatypes.graph.ConnectivityMeasure">
                    <field name="array_data" reference="result['wlq']"/>
                    <field name="connectivity" reference="inputs['A_gid']"/>
                    <field name="title" value="Walk length distribution"/>
                </output>
            </outputs>
        </algorithm>

        <algorithm name="Reachability and distance matrices (Algebraic path count)" identifier="RDA">
            <code value="[R,D] = reachdist(CIJ);"/>
            <matlab_file value="reachdist.m"/>
            <inputs>
                <input required="True">
                    <name value="CIJ"/>
                    <label value="Binary (directed/undirected) connection matrix:"/>
                    <type value="tvb.datatypes.connectivity.Connectivity" field="weights"/>
                </input>
            </inputs>
            <outputs>
                <output type="tvb.datatypes.graph.ConnectivityMeasure">
                    <field name="array_data" reference="result['R']"/>
                    <field name="connectivity" reference="inputs['CIJ_gid']"/>
                    <field name="title" value="Reachability matrix"/>
                </output>
                <output type="tvb.datatypes.graph.ConnectivityMeasure">
                    <field name="array_data" reference="result['D']"/>
                    <field name="connectivity" reference="inputs['CIJ_gid']"/>
                    <field name="title" value="Distance matrix"/>
                </output>
            </outputs>
        </algorithm>
                   
    </algorithm_group>
</tvb>

=== liadomide/EduPack/tvb-framework/tvb/adapters/analyzers/matlab_interfaces/bct.xml
<?xml version="1.0"?>

<tvb xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../core/schema/tvb.xsd">

    <algorithm_group name="bct" type="tvb.adapters.analyzers.group_matlab_adapter.MatlabAdapter" additionalPath="externals/BCT"
                     uiName="Modularity Algorithms" description="Brain Connectivity Toolbox" label="Choose Modularity Algorithm:">
        <!-- Modularity -->

        <algorithm name="Optimal Community Structure and Modularity" identifier="OCSM">
            <code value="[Ci,Q] = modularity_dir(W);"/>
            <matlab_file value="modularity_dir.m"/>
            <inputs>
                <input required="True">
                    <name value="W"/>
                    <label value="Directed (weighted or binary) connection matrix:"/>
                    <type value="tvb.datatypes.connectivity.Connectivity" field="weights"/>
                </input>
            </inputs>
            <outputs>
                <output type="tvb.datatypes.graph.ConnectivityMeasure">
                    <field name="array_data" reference="result['Ci']"/>
                    <field name="connectivity" reference="inputs['W_gid']"/>
                    <field name="title" value="Optimal Community Structure"/>
                </output>
                <output type="tvb.datatypes.mapped_values.ValueWrapper">
                    <field name="data_value" reference="float(result['Q'])"/>
                    <field name="data_type" value="float"/>
                    <field name="data_name" value="Maximized Modularity"/>
                </output>
            </outputs>
        </algorithm>

        <algorithm name="Optimal Community Structure and Modularity (Louvain)" identifier="OCSML">
            <code value="[Ci,Q] = modularity_louvain_und(W);"/>
            <matlab_file value="modularity_louvain_und.m"/>
            <inputs>
                <input required="True">
                    <name value="W"/>
                    <label value="Undirected (weighted or binary) connection matrix:"/>
                    <type value="tvb.datatypes.connectivity.Connectivity" field="weights"/>
                </input>
            </inputs>
            <outputs>
                <output type="tvb.datatypes.graph.ConnectivityMeasure">
                    <field name="array_data" reference="result['Ci']"/>
                    <field name="connectivity" reference="inputs['W_gid']"/>
                    <field name="title" value="Optimal Community Structure"/>
                </output>
                <output type="tvb.datatypes.mapped_values.ValueWrapper">
                    <field name="data_value" reference="float(result['Q'])"/>
                    <field name="data_type" value="float"/>
                    <field name="data_name" value="Modularity"/>
                </output>
            </outputs>
        </algorithm>

        <algorithm name="Optimal Community Structure and Modularity (Louvain-Sign)" identifier="OCStMLS">
            <code value="[Ci,Q] = modularity_louvain_und_sign(W, qtype);"/>
            <matlab_file value="modularity_louvain_und_sign.m"/>
            <inputs>
                <input required="True">
                    <name value="W"/>
                    <label value="Undirected (weighted or binary) connection matrix with positive and negative weights:"/>
                    <type value="tvb.datatypes.connectivity.Connectivity" field="weights"/>
                </input>
                <input required="True">
                    <name value="qtype"/>
                    <label value="Modularity Type:"/>
                    <description value="See Rubinov and Sporns, 2011"/>
                    <type value="select" default="sta">
                        <options>
                            <option name="sta [Q_*]" value="sta"/>
                            <option name="pos [Q_+]" value="pos"/>
                            <option name="smp [Q_simple]" value="smp"/>
                            <option name="gja [Q_GJA]" value="gja"/>
                            <option name="neg [Q_-]" value="neg"/>
                        </options>
                    </type>
                </input>
            </inputs>
            <outputs>
                <output type="tvb.datatypes.graph.ConnectivityMeasure">
                    <field name="array_data" reference="result['Ci']"/>
                    <field name="connectivity" reference="inputs['W_gid']"/>
                    <field name="title" value="Community Affiliation Vector"/>
                </output>
                <output type="tvb.datatypes.mapped_values.ValueWrapper">
                    <field name="data_value" reference="float(result['Q'])"/>
                    <field name="data_type" value="float"/>
                    <field name="data_name" value="Modularity"/>
                </output>
            </outputs>
        </algorithm>

        <algorithm name="Optimal Community Structure and Modularity (Undirected)" identifier="OpCSMU">
            <code value="[Ci,Q] = modularity_und(W);"/>
            <matlab_file value="modularity_und.m"/>
            <inputs>
                <input required="True">
                    <name value="W"/>
                    <label value="Directed (weighted or binary) connection matrix:"/>
                    <type value="tvb.datatypes.connectivity.Connectivity" field="weights"/>
                </input>
            </inputs>
            <outputs>
                <output type="tvb.datatypes.graph.ConnectivityMeasure">
                    <field name="array_data" reference="result['Ci']"/>
                    <field name="connectivity" reference="inputs['W_gid']"/>
                    <field name="title" value="Optimal Community Structure"/>
                </output>
                <output type="tvb.datatypes.mapped_values.ValueWrapper">
                    <field name="data_value" reference="float(result['Q'])"/>
                    <field name="data_type" value="float"/>
                    <field name="data_name" value="Maximized Modularity"/>
                </output>
            </outputs>
        </algorithm>

    </algorithm_group>
</tvb>
