=== liadomide/EduPack/tvb/core/schema/events.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.thevirtualbrain.org/tvb"
xmlns="http://www.thevirtualbrain.org/tvb">

    <xs:element name='events'>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="event" type="eventType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

	<xs:complexType name='eventType'>
            <xs:all>
                <xs:element name="launcher" type="launcherType" minOccurs="0" maxOccurs="1"/>
                <xs:element name="adapter" type="adapterType" minOccurs="0" maxOccurs="1"/>
                <xs:element name="method" minOccurs="1" maxOccurs="1">
	                <xs:complexType>
				        <xs:attribute name="name" type="xs:string" use="required"/>
				        <xs:attribute name="operation-hidden" type="xs:string" use="optional"/>
				    </xs:complexType>
				</xs:element>
                <xs:element name="args" type="argumentsType" minOccurs="0" maxOccurs="1"/>
            </xs:all>
            <xs:attribute name="hookpoint" type="xs:string" use="required"/>
            <xs:attribute name="type" type="xs:string" use="required"/>
            <xs:attribute name="delay" type="xs:string" use="optional"/>
	</xs:complexType>
	
	<xs:complexType name="argumentsType">
        <xs:sequence>
             <xs:element name="arg" type="argType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
      
	<xs:complexType name="argType">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="value" type="xs:string" use="required"/>
        <xs:attribute name="type" type="xs:string" use="optional"/>
        <xs:attribute name="module" type="xs:string" use="optional"/>
    </xs:complexType>
    
    <xs:complexType name="adapterType">
        <xs:attribute name="module" type="xs:string" use="required"/>
        <xs:attribute name="class" type="xs:string" use="required"/>
        <xs:attribute name="uid" type="xs:string" use="optional"/>
    </xs:complexType>
    
    <xs:complexType name="launcherType">
        <xs:attribute name="module" type="xs:string" use="required"/>
        <xs:attribute name="class" type="xs:string" use="required"/>
        <xs:attribute name="instance" type="xs:string" use="optional"/>
    </xs:complexType> 
	
</xs:schema>

=== liadomide/EduPack/tvb-framework/tvb/config/events.xml
<?xml version="1.0"?>

<events  xmlns="http://www.thevirtualbrain.org/tvb"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../core/schema/events.xsd">

	<!-- Supported variables to be available from runtime are so far $$CURRENT_USER$$ and $$CURRENT_PROJECT$$-->

 	<event hookpoint="UserService.create_admin" type="generic">
        <launcher module="tvb.core.services.import_service" class="ImportService" instance="True"/>
        <method name="import_project_structure"/>
        <args>
            <arg name='uploaded' value="Default_Project.zip" module='tvb_data' type="file" />
            <arg name="user_id" value="$$CURRENT_USER$$.id" type="runtime"/>
        </args>
    </event>

    <event hookpoint="UserService.create_user" type="generic">
        <launcher module="tvb.core.services.project_service" class="ProjectService" instance="True"/>
        <method name="add_member_to_project"/>
        <args>
            <arg name="project_gid" value="3ccbe88a-47ca-11e4-809c-3c075431bf56" type="str"/>
            <arg name="user_id" value="$$CURRENT_USER$$.id" type="runtime"/>
        </args>
    </event>


    <event hookpoint="CodeVersionsManager.update.4455" type="adapter">
        <adapter module="tvb.adapters.uploaders.obj_importer" class="ObjSurfaceImporter"/>
        <method name="launch" operation-hidden="true"/>
        <args>
            <arg name='data_file' value="eeg_cap.obj" module='tvb_data.obj' type="file" />
            <arg name='surface_type' value='EEG Cap' type='str' />
        </args>
    </event>
    <event hookpoint="CodeVersionsManager.update.4455" type="adapter">
        <adapter module="tvb.adapters.uploaders.obj_importer" class="ObjSurfaceImporter"/>
        <method name="launch" operation-hidden="true"/>
        <args>
            <arg name='data_file' value="face_surface.obj" module='tvb_data.obj' type="file" />
            <arg name='surface_type' value='Face' type='str' />
        </args>
    </event>
    
    
    <event hookpoint="CodeVersionsManager.update.4750" type="adapter">
        <adapter module="tvb.adapters.uploaders.sensors_importer" class="Sensors_Importer"/>
        <method name="launch"/>
        <args>
            <arg name='sensors_file' value="internal_39.txt.bz2" module='tvb_data.sensors' type="file" />
            <arg name='sensors_type' value='Internal Sensors' type='str' />  
        </args>
    </event>


    <event hookpoint="CodeVersionsManager.update.6093" type="adapter">
        <adapter module="tvb.adapters.uploaders.obj_importer" class="ObjSurfaceImporter"/>
        <method name="launch" />
        <args>
            <arg name='data_file' value="face_surface.obj" module='tvb_data.obj' type="file" />
            <arg name='surface_type' value='Face' type='str' />
        </args>
    </event>


    <event hookpoint="CodeVersionsManager.update.6600" type="generic">
        <launcher module="tvb.core.services.import_service" class="ImportService" instance="True"/>
        <method name="import_project_structure"/>
        <args>
            <arg name='uploaded' value="Default_Project.zip" module='tvb_data' type="file" />
            <arg name="user_id" value="$$CURRENT_USER$$.id" type="runtime"/>
        </args>
    </event>

</events>
